- src/components/layout/LayoutDefault.vue
> style : LayoutDefault 에서 사이드바 너비 고정

- src/components/common/SidebarItem.vue
- src/components/layout/sidebar/SidebarAdminCsQuizGroup.vue
- src/components/layout/sidebar/SidebarAdminItNewsGroup.vue
- src/components/layout/sidebar/SidebarAdminReportGroup.vue
- src/features/admin/AdminMainView.vue
> fix sideBar

- src/features/main/views/MainView.vue
> feat: 페이지 정렬 수정

- src/features/admin/AdminMainView.vue
- src/features/admin/csquiz/views/CsQuizDetailView.vue
- src/features/admin/csquiz/views/CsQuizWriteView.vue
- src/features/csquiz/views/CsQuizMainView.vue
- src/features/csquiz/views/CsQuizResultView.vue
- src/features/csquiz/views/TakeCsQuizView.vue
> [feature #9] CsQuiz, admin main 부분 공통 컴포넌트 추가(헤더)

- src/features/user/router.js
- src/features/user/views/UserSignUpGoogleView.vue
- src/features/user/views/UserSignUpView.vue
> feat: 유저 구글 회원가입 페이지 구현

- src/features/mypage/components/MyPageBoard.vue
- src/features/mypage/components/MyPageButtonBlue.vue
- src/features/mypage/components/MyPageButtonUpdate.vue
- src/features/mypage/components/MyPageButtonWhite.vue
- src/features/mypage/components/MyPageContent.vue
- src/features/mypage/components/MyPageProfile.vue
- src/features/mypage/views/MyPage2View.vue
> feat: 유저 마이페이지 수정

- src/features/user/api.js
- src/main.js
> feat: App.vue 렌더링 시 RefreshToken를 통한 정보 불러오기 구현

- src/api/axios.js
- src/main.js
> [Fix #74] axios interceptor refresh 경로 수정

- src/features/interview/api.js
- src/features/interview/components/InterviewItem.vue
- src/features/interview/components/InterviewQuestionCard.vue
- src/features/interview/components/InterviewReexecuteModal.vue
- src/features/interview/components/ReexecutedListModal.vue
- src/features/interview/router.js
- src/features/interview/views/InterviewDetailView.vue
- src/features/interview/views/InterviewListView.vue
- src/features/interview/views/InterviewProgressView.vue
- src/features/interview/views/InterviewRunView.vue
> feat: 모의 면접 API 연결

- src/features/interview/api.js
- src/features/interview/views/InterviewDetailView.vue
- src/features/interview/views/InterviewListView.vue
- src/features/interview/views/InterviewProgressView.vue
- src/features/interview/views/InterviewRunView.vue
> feat: 모의 면접 breadcrumb 추가

- src/components/layout/Header.vue
> [feat #84] 헤더 이미지 경로 수정

- src/components/layout/Sidebar.vue
> refactor: Sidebar 관리자 노출 섹션 확장

- src/features/devti/api.js
- src/features/devti/components/DevtiResultSection.vue
- src/features/devti/views/DevtiResultView.vue
- src/features/devti/views/DevtiTestView.vue
> feat : DevTI api 연결

- src/features/comment/components/CommentItem.vue
- src/features/interaction/components/InteractionBar.vue
> [feature #76] 좋아요, 북마크 회원 비회원 기능 수정

- src/features/interview/components/SortDropdown.vue
- src/features/interview/views/InterviewDetailView.vue
- src/features/interview/views/InterviewListView.vue
- src/features/interview/views/InterviewRunView.vue
> feat: 면접 부가 사항 설정

- src/features/user/api.js
- src/features/user/components/UserItNewsSub.vue
- src/features/user/router.js
- src/features/user/views/Oauth2SuccessView.vue
- src/features/user/views/UserLoginGeneralView.vue
- src/features/user/views/UserLoginView.vue
- src/features/user/views/UserSignUpGoogleView.vue
- vite.config.js
> feat: 유저 구글 로그인 토큰 처리

- src/features/mypage/api.js
- src/features/mypage/components/MyPageModify2.vue
- src/features/mypage/components/MyPageVerify.vue
> feat: 마이페이지 이메일 수정 기능 수정

- src/features/interview/components/ReexecutedListModal.vue
- src/features/interview/views/InterviewDetailView.vue
> feat : 재실행 면접방 목록 창 닫기

- src/features/mypage/components/MyPageModify2.vue
- src/features/mypage/components/MyPageModify3.vue
- src/features/mypage/components/MyPageVerify.vue
> [feat #138] 마이페이지 비밀번호 변경 코드 수정

- src/components/common/PagingBar.vue
- src/features/admin/report/components/ReportList.vue
Closes #{이슈 번호}
- reportList 내용 width 크기 고정
- #{이슈 번호}
> report List width Fix

- src/features/main/api.js
- src/features/main/components/MainContentBoard.vue
- src/features/main/views/MainView.vue
> feat: 메인 페이지 자유게시판 직무게시판 내용 수정

- src/features/main/views/MainView.vue
> [feat] 메인 페이지 자유게시판 직무게시판 내용 수정

- src/features/chatting/views/ChattingView.vue
> 채팅 차단 시 오류 수정

- src/features/main/components/MainContentBoard.vue
- src/features/mypage/views/MyPageEditView.vue
- src/features/mypage/views/MyPageView.vue
> [feat] 메인페이지 수정, 마이페이지 헤더 수정

- src/features/devti/views/DevtiIntroView.vue
- src/features/devti/views/DevtiResultView.vue
- src/features/devti/views/DevtiTestView.vue
- src/features/user/views/Oauth2SuccessView.vue
- src/features/user/views/UserDeleteView.vue
- src/features/user/views/UserFindLoginIdView.vue
- src/features/user/views/UserLoginGeneralView.vue
- src/features/user/views/UserLoginView.vue
- src/features/user/views/UserResetPwView.vue
- src/features/user/views/UserSignUpGeneralView.vue
- src/features/user/views/UserSignUpGoogleView.vue
- src/features/user/views/UserSignUpView.vue
> feat: 유저, 마이페이지 헤더 반영

- src/features/mypage/components/MyPageProfile.vue
> feat: 마이페이지 수정
